#!/bin/bash
set -euo pipefail
JSONNET=${JSONNET:-jsonnet}

cd tests
# jb update
for d in *.jsonnet; do
  name=${d%%.jsonnet}
  $JSONNET "$d" -J .. -J vendor -S -c -m "$name"
done
git diff --exit-code
